#!/bin/bash
# https://github.com/unix1984/btrfs-rmdir
# example:
# 1) echo only: btrfs-rmdir -e /path/to/dir
# 2) delete!: btrfs-rmdir -d /path/to/dir
# set -x

VER=1.1

path=$2

while getopts "edh" option; do
case ${option} in
    e ) 
    for i in `ls -1 ${path} | awk {'print $1'}`; do echo echo: btrfs subvolume delete ${path}/$i ; done
      ;;
    d ) 
    for i in `ls -1 ${path} | awk {'print $1'}`; do btrfs subvolume delete ${path}/$i ; done
      ;;
    h ) 
    echo "Version = ${VER}"
    echo
    echo "*Example:"
    echo "1) echo only: btrfs-rmdir -e /path/to/dir"
    echo "2) delete!: btrfs-rmdir -d /path/to/dir"
    echo
    echo "[-e] - echo only"
    echo "[-d] - delete all subvolumes"
    echo "[-h] - This help"
    echo
      ;;
  esac
done
